linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - revive
    - ineffassign
    - vet
    - unused
    - misspell
  disable:
    - errcheck

run:
  deadline: 4m
  skip-dirs:
    - out
